### ISSUE TITLE
Not decrypting in Android

### ISSUE THREAD

**Issue by sumeet-mibo** [chaudhuri-ab/CrossPlatformCiphers#4]
Encrypted text in php is not decrypting in Android  with **AES/CBC/PKCS5Padding**  
Getting following error

`javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

  at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
  at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
  at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:365)
 at javax.crypto.Cipher.doFinal(Cipher.java:2055)`

**Comment by renalpha** [comment]
I experience the same issue

**Comment by renalpha** [comment]
> I experience the same issue

Fixed it. Sorry. I was using a wrong key. Probally your doing the same.
